# Site settings
title: "Rahul \u5350 Neha"
description: |
    Jalna, Maharashtra

    January 25, 2019
owner: Pratik Chaudhari
first_published: 2018
email: cp.baba@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.rahulneha.com" # the base hostname & protocol for your site

social:
  instagram: #rahulneha

# Build settings
markdown: kramdown
